Load data change
simonsobs/so3g pull request #122
Opened 2022-03-18 16:35 UTC by jeffiuliano

This allows one to specify a `pre_proc_dir` -- a directory where pickled `HKScannerArchive` objects can be stored -- so that they do not need to be re-created on every call.  Can be passed to `HKArchiveScanner`, to be used in the `process_file_with_cache` method (which just calls the normal `process_file` method if no `pre_proc_dir` is specified).  This is then used in the `load_range` function, which now also passes the start/end times `hksc.simple`. 

If this flag isn't used, the behavior/syntax _should_ be unchanged.

The point of this is to speed up repeated loading from the same g3 files (by using this flag).  When testing it definitely seems faster, though not by quite as much as I had expected.

2022-03-22 17:06 UTC, mhasself requested changes
Thanks for this.  It was always the intention that the scan results be saved somehow, and this does it.

I have highlighted some minor concerns, and nitpicks about formatting.  Also adding @kmharrington to review.

2022-03-22 17:06 UTC, mhasself commented on python/hk/getdata.py
> +        self.providers.update(hksc.providers)
Unless I forget how this works, both self.providers and hksc.providers should be empty at this point (they are emptied by the flush() call, which is performed by default at the end of each file).  So I suspect you don't need this / it is misleading to include this.

2022-03-22 23:07 UTC, kmharrington commented
I agree with the permissions feedback from Matthew. Does this significantly speed up your use case? I had been imagining some mechanism of just holding an HKArchiveScanner in memory between calls to `load_range`, but if this version works out then I can accept it. (@sanahabhimani  it does make me really want a non-bootstrapped version though :-D )

2022-03-23 14:30 UTC, jeffiuliano commented on python/hk/getdata.py
> +        self.providers.update(hksc.providers)
Yeah I wasn't sure if there were cases where it would be non-empty and so needed.  You're right though, it looks like it is emptied by flush.

2022-03-23 14:35 UTC, jeffiuliano commented
> I agree with the permissions feedback from Matthew. Does this significantly speed up your use case? I had been imagining some mechanism of just holding an HKArchiveScanner in memory between calls to `load_range`, but if this version works out then I can accept it. (@sanahabhimani it does make me really want a non-bootstrapped version though :-D )

So processing the file once is pretty fast.  In principle then we could do something like you suggest and keep it in memory between calls.  It's just that I didn't think of a non-complicated way to do that which didn't require a lot of book-keeping by the load_range user (like realizing that they were accessing the same g3 file a bunch and so separately making the scanner object and passing it).  Using something in /tmp for the pre_proc_dir would be similar in effect I suppose.

2022-03-23 17:34 UTC, jeffiuliano commented on python/hk/getdata.py
> +                os.makedirs( os.path.dirname(path), mode=0o777)
yeah good point.  Switched to os.chmod and flag for permissions.  in principle each user could have their own, but it makes integrating it into some of the tools in LATR Validation easier if it can be a shared directory.

2022-04-18 19:48 UTC, jeffiuliano commented
While we have this PR for the getdata stuff, one more small change.  I ran into a weird issue where for some small time ranges, certain fields would cease to exist, so I added a non-strict mode to `load_range` that moves on rather than raising a KeyError (defaults to the normal behavior though).

2022-04-22 14:16 UTC, mhasself requested changes
Thanks  -- a few more comments (sorry to drag this out).

2022-04-22 14:16 UTC, mhasself commented on python/hk/getdata.py
> +
Insufficient documentation of "strict".

Wrap the pre_proc_mode description to < 78 columns please.

2022-04-22 14:16 UTC, mhasself commented on python/hk/getdata.py
> +        If self.pre_proc_dir is specified (not None), it will load pickled HKArchvieScanner objects and
This still says Archvie.

2022-04-22 14:16 UTC, mhasself commented on python/hk/getdata.py
> +        If self.pre_proc_dir is specified (not None), it will load pickled HKArchvieScanner objects and
Also please wrap docstrings at ~78th column or earlier.

2022-04-22 14:16 UTC, mhasself commented on python/hk/getdata.py
> +            t,x = cat.simple(field, start=start_ctime, end=stop_ctime)
Instead of skipping the field entirely, would it make sense to instead return empty arrays?

Seems like that is a sensible default behavior, really. (Would like to hear @kmharrington opinion on that.)

2022-04-22 14:16 UTC, mhasself commented on python/hk/getdata.py
> +                hk_logger.error(f'{e} -- skipping field')
.warning instead of .error, I think.

2022-07-27 19:26 UTC, jeffiuliano commented on python/hk/getdata.py
> +            t,x = cat.simple(field, start=start_ctime, end=stop_ctime)
Since it returns a dict ultimately rather than a list, it's not so different in use-case.  I would have a slight preference for assuming that data exists when I see a key in the returned data, but I think either would be reasonable behavior.

2022-07-27 19:27 UTC, jeffiuliano commented
Sorry it took a while to get back to this, but I made the suggested changes other than the default behavior when a field is missing.  Happy to change that too if we decide that's what we want.

2022-08-02 03:08 UTC, mhasself approved these changes
Had a chance to give this another whirl today -- definitely will speed things up in certain cases.

I think this isn't the end of the story but I'd definitely recommend folks working with long stretches of HK data to use this.

2022-08-02 03:09 UTC, merged