Bilinear
simonsobs/so3g pull request #157
Opened 2023-08-24 19:37 UTC by amaurea

Support for bilinear mapmaking. Standard nearest neighbor mapmaking is still the default, and its performance is unchanged in my tests.

2023-08-24 20:48 UTC, amaurea commented
I'll make pull requests for sotodlib and pwg-scripts that depend on this when this one is accepted.

2023-08-30 23:20 UTC, mhasself requested changes
Preliminary review, see comments -- haven't been able to run this yet due to conda / glibc conflicts... but will try on a different system tomorrow.

I think my biggest concern is interface breakage -- it seems like this changes the shape of the RangesMatrix "threads" object, even in the case of interpol="nn".  So existing sotodlib.coords code, if it inspected threads for some reasons, would probably choke.  I am not sure whether any of the important code does so.  Alas there don't seem to be any sotodlib unit tests that probe pmat, so that doesn't help us.

2023-09-05 11:56 UTC, amaurea commented on src/Projection.cxx
> +    int GetPixels(int i_det, int i_time, const double *coords, int pixinds[interp_count][index_count], FSIGNAL pixweights[interp_count]);
It all works for me though! This is all tested and runs, and produces the right output.  interp_count *is* an integral constant-expression. I think somehow something must be missing from this pull request since you're getting inconsistent results from what I get, when we both use gcc. But I'll look at the approach you describe here (though it seems more limited, as the number of pixels that are touched in a given interpolation scheme could in theory on the pixelization itself).

2023-09-05 12:39 UTC, amaurea commented
> I think my biggest concern is interface breakage -- it seems like this changes the shape of the RangesMatrix "threads" object, even in the case of interpol="nn". So existing sotodlib.coords code, if it inspected threads for some reasons, would probably choke. I am not sure whether any of the important code does so. Alas there don't seem to be any sotodlib unit tests that probe pmat, so that doesn't help us.

Yes, it does make a breaking change, but I went through all sotodlib code I could find that uses this, and updated it accordingly. Did I miss anything?

I think this breaking change is worth it because the new structure is both general enough to handle basically any parallelization scheme while also having practically no overhead. I think it would be a bad idea to drag around two different shapes for the threads object depending on the interpolation used or the threading approach used. Maybe we can discuss this in a meeting if you disagree.

2023-11-27 10:35 UTC, mhasself approved these changes
Ok, let's get this out there!

2023-11-27 10:35 UTC, merged