Healpix mapmaker
simonsobs/so3g pull request #179
Opened 2024-05-16 16:03 UTC by earosenberg

2024-06-03 16:23 UTC, mhasself requested changes
Sorry it took me a while to get to this.  This is appreciated!

A few comments inline.  Also:
- The demo is helpful, but there should be unit tests too (in test/).  (See test_proj_eng.py ... I think it's best if unit tests run quickly, i.e. using very small problems for the trials.)
- Add some basic instructions to the docs (doesn't have to be exhaustive; just a starting point / example).

2024-06-03 16:23 UTC, mhasself commented on demos/demo_proj_hp.py
> +    proj.assign_threads(asm, 'tiles') ## Assign threads
To test threading, you have to capture the return value
```
  threads = proj.assign_threads(...)
```
and pass it explicitly to to_map / to_weights.  (I tried this, it works well.)

2024-06-03 16:23 UTC, mhasself commented on demos/demo_proj_hp.py
> +    ## Make a tiled map ##
The demo (or ideally tests) should include testing from_map, too.

My naive attempt:
```
        proj = so3g.proj.ProjectionistHealpix.for_healpix(nside, nside_tile=None)
        signal2 = proj.from_map(rhs, asm)
```
Caused to a segfault.  So that needs to be fixed.  If implementing `from_map` is problematic for some reason, then at least protect the user from segfault with appropriate argument checks.

2024-06-03 16:23 UTC, mhasself commented on include/healpix_bare.h
> + *  Licensed under a 3-clause BSD style license - see LICENSE
In the so3g LICENSE file, append a section like
```
healpix_bare.h and healpix_bare.c are included in this source repository under the terms of the following license:
...
```
and include the license from healpix.

2024-06-10 14:19 UTC, earosenberg commented
Thanks for the detailed comments! With respect to the docs, my restructuring of the `Projectionist` class means that the automatic reference for `Projectionist` is now missing the shared methods belonging to the parent class. I could just add all three classes (`_ProjectionistBase`, `Projectionist`, `ProjectionistHealpix`) to the automatic docs, but don't know if there's a preferred solution?

2024-06-10 18:34 UTC, earosenberg commented
I believe these commits address all of the above points, except for the docs issue I mentioned in my previous comment

2024-06-18 18:16 UTC, mhasself requested changes
Thanks for the additional fixes.  This is almost ready.

For the Projectionist docs, I think you just need to put all 3 classes in the autodocs, and then create an explicit link in the docstring for the two subclasses saying "see also the methods defined in base class, ...".  I think it's dangerous and annoying to duplicate docstring text ... but helpful to provide clickable links in the rendered documentation to the one source of truth.  (This approach is already in there, where method docstrings don't _all_ explain what is meant by arguments "assembly", "comps", etc ... but rather that's explained in the class docstring.  All that stuff in the Projectionist docstring should probably go in the base class docstring, then, and just a link remains (along with everything specific to RectPix).)

2024-06-19 14:53 UTC, earosenberg commented on python/proj/coords.py
> +    def az_el(cls, t, az, el, roll=None, site=None, weather=None, **kwargs):
Not directly; it was added because extra qpoint args were necessary to get a good match to Toast sims in my validation tests. Can remove from this PR if you want, else I'll add a note to the docstring like you say

2024-06-24 19:09 UTC, mhasself approved these changes
I have a few minor comments before merge, but approving now.

I'm really pleased to have these capabilities in so3g -- thanks again for taking this on!

2024-06-24 19:09 UTC, mhasself commented on python/proj/wcs.py
> +        See parent class documentation for full description.
It's not really necessary to redefine this method, right?  There's nothing proj specific about get_coords.  I know the default version uses CAR, but that's true, under the hood, for the HP projector too.

So... please remove this, and just update the inherited get_coords docstring if you feel it is not general enough.

2024-06-25 01:33 UTC, mhasself commented
btw @earosenberg Please squash this on merge (or before).

2024-06-25 10:00 UTC, earosenberg commented on python/proj/wcs.py
> +        See parent class documentation for full description.
Agree it's not needed in principle. As written there is a technical problem, in that the inherited get_coords will try to initialize a CAR ProjEng using the Healpix _get_pixelizor_args info (nside, etc) and crash. 
I can add a small check to the parent function to call the HP rather than CAR ProjEng, or there are other solutions (eg add a default arg to call 'CAR' with a minimal re-definition in the Healpix case to call 'HP', or a bit more work in the Healpix case to make a proper CAR Projectionist), or else we can leave it as is. Do you have a preference?

2024-06-25 11:04 UTC, mhasself commented on python/proj/wcs.py
> +        See parent class documentation for full description.
Ah, right.  Ok, that's a good enough reason.  Leave it in.

2024-06-27 01:16 UTC, mhasself approved these changes
Great - squash and rebase and we're done.

2024-06-27 09:38 UTC, merged