Block moment
simonsobs/so3g pull request #180
Opened 2024-05-20 16:57 UTC by skhrg

Used by https://github.com/simonsobs/sotodlib/pull/807

2024-06-03 19:54 UTC, mhasself requested changes
Thanks.  A few things:

- These functions assume the arrays (buffers) or C-ordered.  But nothing enforces that.  So, segfault city.  It's pretty easy to generalize these for arbitrary strides; see other uses of BufferWrapper.  Or else check that it's C-ordered and throw an informative error.  But do not allow for segfaults.
- Add docstrings to the bp::def entries.
- Add tests.
- The rest of so3g formats `if` and `for` blocks like this:
```
if (condition) {
    block;
}
```
So please add that space and remove that extra new line.

2024-06-26 12:36 UTC, skhrg commented
@mhasself I think this is good to go, could you take another look? I'd like this get this faster jumpfinder out in the wild soon.

2024-06-26 15:47 UTC, mhasself requested changes
Some comments inline.

I have some reservations about the jump finding algorithm.  My immediate reactions were (a) this relies on "blocks" too much and (b) I don't understand what kind of jumps this will detect / not detect.

Adapting your unit test case, I loop over several signals, where the jump is shifting to the right.  Note the threshold for detection is substantially higher than the true jump size -- 1.2.

```
for offset in range(20):
    a = np.zeros((1, 100), dtype="float32", order="C")
    a[0, 50+offset:] += 1
    b = np.zeros((1, 100), dtype="int32", order="C")
    min_size = np.ones(1, dtype="float32", order="C")*1.2
    so3g.matched_jumps(a, b, min_size, 10)
    flagged = np.where(b)[1]
    print(flagged)
```

What I get is:
```
[48 49 50]
[49 50]
[51]
[52]
[53 54]
[53 54 55]
[54 55]
[56]
[57]
[58 59]
[58 59 60]
[59 60]
[61]
[62]
[63 64]
[63 64 65]
[64 65]
[66]
[67]
[68 69]
```

So the sensitivity of the finder varies depending on where the jump is relative to the window edge.  I think we can cook up versions of this that will have a more consistent kernel.  It will probably involve a boxcar filter -- this is easy to implement and is the continuous limit of your block-moment based approach.

2024-06-26 21:43 UTC, skhrg commented on src/array_ops.cxx
> +            int i = ioff + si;
Ah yes I see I should have done `idx = ioff` below to do what I want, good catch.

Yeah I can change things to grab a 1d pointer to make that better.

2024-06-26 21:51 UTC, skhrg commented
On the sensitivity of the jumpfinder caring about the location relative to the edge of the window. This is known with calculalable effects. The shifted window scheme here was chosen in such a way that there is some garunteed minumum sensitivity. See https://simonsobs.atlassian.net/wiki/spaces/PRO/pages/389939204/Matched+Filter+Jump+Finding for an explanation (page is slightly out of date but the math for this is still accurate).

A boxcar would indeed give us maximum consistency and sensitivity since you will always have a case when the jump is in the center of the kernal which maximizes the sensitivity. But I dont think that is necessary since we pad anyways.

Also the jumps getting caught with min size greater than the jump size I beleive is becuase I correct for a samples worth of slop in min size. That can be removed, I dont recall the exact edge case I was worried about when I added that.

2024-07-03 21:27 UTC, skhrg commented
Ah actually, the correct thing to do is to determine the sensitivity as a function of distance from the window edge and compare to  `min_size*sensitivity` . What I do now is use the sensitivity at the minimum gaurunteed distance from the edge given the phased block approach.

I'll work out the math but I think with that (and adding a cutoff where we just skip and don't bother checking since the other block will always do better) we should get a consistent and well behaved kernel.

2024-07-11 20:03 UTC, mhasself requested changes

2024-07-11 20:03 UTC, mhasself commented on src/array_ops.cxx
>  void _clean_flag(int* flag_data, int width, int ndet, int nsamp)
I think a more efficient implementation would simply step through each sample, keeping track of how long the current block of 1s is.  When you encounter a 0, either zero out the previous block (if it wasn't long enough) or just leave it be.  That way you don't need a separate scratch buffer, and there's a lot less thrashing around of values (setting them to zero then setting them back to 1 later).  I'm not going to insist on this, since the performance difference isn't going to hurt unless we have very dense flags and a large value for `width`.

2024-07-11 20:07 UTC, mhasself commented
> While yes I know that taking the continuous limit solves this problem as well, one of the reasons for going with the phased blocks like I did here was to reduce the computational complexity since making it continuous will make it `block_size/2` times slower.

I am skeptical that you'd suffer a performance cost of this magnitude.  But I admit I haven't thought about it super carefully.

> @mhasself let me know if that sounds sane.

Let's go with this for now, sure, but I will welcome something with less structured behavior in the future...

2024-07-12 16:07 UTC, skhrg commented on src/array_ops.cxx
>  void _clean_flag(int* flag_data, int width, int ndet, int nsamp)
You are correct, The current implementation was ported over from python and there I did it like this because I could write this down in terms of vectorized numpy functions. In C++ an accumulator and an if statement is going to be faster and (more importantly) more readable.

2024-07-16 16:17 UTC, skhrg commented
Behavior is more consistent now. If you turn off `samp_correction` then it gives you exactly what I calculate with pen and paper. Leaving that on for now but I could be convinced its unneeded paranoia.

2024-07-16 18:24 UTC, mhasself requested changes
Minor comments.  Then rebase to make it mergeable and prepare for a final review...

2024-07-16 18:24 UTC, mhasself commented on src/array_ops.cxx
> +                }
Remove debug

2024-07-16 22:21 UTC, skhrg commented
Sounds good. Any opposition to me squashing the whole PR into one commit?

2024-07-17 00:52 UTC, skhrg commented on src/array_ops.cxx
> +            if(det_flag[si]==0) {
In the `det_flag[si]==0` and `count == 0` case this makes the else trigger and increments count.
I could change the `count = count + 1` line to `count = count + det_flag[si]` or switch to an `elif` to sidestep this (but I am morally opposed to elifs without an `else`)

2024-07-17 13:41 UTC, mhasself commented on src/array_ops.cxx
> +            if(det_flag[si]==0) {
Ah of course, never mind.

2024-07-17 13:41 UTC, mhasself commented
> Sounds good. Any opposition to me squashing the whole PR into one commit?

Rebase + squash into one commit would be perfect.  Thanks!

2024-07-18 16:18 UTC, mhasself approved these changes
Thanks!

2024-07-18 16:18 UTC, merged