Implement linear interpolation function with GSL
simonsobs/so3g pull request #187
Opened 2024-10-09 14:59 UTC by mmccrackan

This branch adds a simple parallelized linear interpolator using GSL.  Since `FindGSL.cmake` was already in SPT3G, only a few lines needed to be added to the so3g cmake file to include it.  I wrote it to mimic the output of `scipy.interpolate.interp1d` when `kind=linear` and `fill_value='extrapolation'`, which is the setup currently used in the sotodlib azss code.  

GSL has a few other interpolation options (linear, cspline, periodic cspline, non-rounded akima spline) which we can also write functions (or accept an interpolation kind argument maybe) for if we need them.  GSL does not handle extrapolation by itself, so the other options will likely need more careful handling of the extrapolation than what I've done here for now (as highlighted in this discussion: https://docs.scipy.org/doc/scipy/tutorial/interpolate/extrapolation_examples.html#extrapolation-tips-and-tricks).

2024-10-11 17:52 UTC, mhasself requested changes
Thanks for this!  Nice to see GSL was easy to bring in.

A few comments mostly about names of things... I'm open to discussion on that.

2024-10-11 17:52 UTC, mhasself commented on src/array_ops.cxx
> +using _gsl_interp_func_pointer = void (*)(const double*, const double*, const double*, T*, const int, const int,
I think we should drop "gsl" from all the definitions here (this and the functions below).  Anything called "gsl" should come from that library.

2024-10-11 17:52 UTC, mhasself commented on src/array_ops.cxx
> +                        gsl_spline* spline, gsl_interp_accel* acc)
You're wrapping at 110 chars or so ... please wrap closer to 78 chars.

2024-10-11 17:52 UTC, mhasself commented on src/array_ops.cxx
> +            "Perform linear interpolation over rows of array with GSL."
Add "This function uses OMP to parallelize over the dets axis."

Add "Vector x must be strictly increasing.  Values for x_interp beyond the domain of x will be computed based on extrapolation."

2024-10-11 17:52 UTC, mhasself commented on src/array_ops.cxx
> +            "  y_interp: interpolated data array (float32) with shape (ndet, nsamp_interp)");
Clarify that y_interp is an output buffer that will be modified/filled by the function.

2024-10-11 17:52 UTC, mhasself commented on src/array_ops.cxx
> +            "gsl_interp1d_cspline(x, y, x_interp, y_interp)"
On second thought we should not include these functions until they are implemented.

If we planned on having a single entry point (`interp(type='spline', ...)`) then doing a partial implementation is more helpful, as it makes a future-proof interface.  But if we're not doing that, better to not pretend there's splines available.

2024-10-11 17:52 UTC, mhasself commented on src/array_ops.cxx
> +    bp::def("gsl_interp1d_linear", gsl_interp1d_linear<float>,
Again on the names... I don't think we need to emphasize these come from gsl.  Can you rename the exposed functions "interp1d32" and "interp1d64".  The spline ones can be `cspline1d{32,64}`.

2024-10-14 14:12 UTC, mmccrackan commented on src/array_ops.cxx
> +    bp::def("gsl_interp1d_linear", gsl_interp1d_linear<float>,
Do you think it might be useful to keep them as "interp1d_linear{32,64}" and "interp1d_cspline{32,64}" instead of just "interp1d{32,64}" and so on as interp1d might refer to a range of interpolation methods?  I think removing gsl from the names is a good idea.

I did try the Boost template overloading to see if we could get rid of the 32 and 64 in the names though I haven't managed to make it work, which I think is due to the fact that both versions have the same boost::python object inputs.

I originally wrote the functions with the string approach you mentioned above (with linear as a default parameter), but I thought separating the functions would be cleaner since we don't need to store and check the allowed types each time the function is called.

2024-10-14 14:31 UTC, mhasself commented on src/array_ops.cxx
> +    bp::def("gsl_interp1d_linear", gsl_interp1d_linear<float>,
Yup, sure, go for `interp1d_{method}{width}`.

Instead of Boost overloading you can do something like [this](https://github.com/simonsobs/so3g/blob/b665511745ac71a4176d4fa270e6a8a3ed01e77e/src/array_ops.cxx#L135) to figure out the type of the input array, and call different functions from the boost-wrapped function.  (If you go that route, please fix the pointer abuse in `get_type`... it should `return res`.)

2024-10-14 15:53 UTC, mmccrackan commented on src/array_ops.cxx
> +    bp::def("gsl_interp1d_linear", gsl_interp1d_linear<float>,
The suggested typing check works great and I've adjusted the interpolation functions to use it.  I've edited the get_dtype function to return res and decrease the reference count on the actual object ob instead of a.

I think the last push should address all of the other requested changes, but let me know if anything else should be changed.

2024-10-15 16:03 UTC, mhasself requested changes
Almost there -- just a request for better exceptions (mostly).  Strides thing is not high priority but consider it.

2024-10-15 16:03 UTC, mhasself commented on src/array_ops.cxx
> +        throw buffer_exception("y must be C-contiguous along last axis");
I recognize this was copied from other code, but it is not right ... buffer_exception expects just the variable name, which it renders as `throw buffer_exception("XYZ") ---> "Argument 'XYZ' does not expose buffer protocol, is not contiguous, or does not export a format."`

You should probably just use `throw ValueError_exception(text)` for these.

The use of "C-contiguous along last axis" is a bit confusing (once again, I see this was taken from elsewhere...).  I think better text would be "Argument 'XYZ' must be a C-contiguous 2d array."

It is possible to relax that constraint and only insist it be contiguous in the 2nd dimension.  That would require making use of strides[0] in the pointer arithmetic.  Very doable -- and helps support partial fills like:
```
   so3g.interp1d_linear(x, y, xx[1000:], yy[:,1000:])
```

2024-10-15 19:24 UTC, mmccrackan commented on src/array_ops.cxx
> +        throw buffer_exception("y must be C-contiguous along last axis");
Okay, I updated the exceptions and I think it should now properly handle the strides for the input data arrays when slicing.  A new test case for the slicing has been added for this.  I also changed some comments, mostly just to match the upper case of the existing code.

2024-10-16 15:07 UTC, mhasself approved these changes
Sorry -- last couple of comments on exception strings...  I'll approve this now though.  Please squash on merge after fixing those error strings.

Thanks for adding the stride handling (and tests!).

2024-10-21 13:42 UTC, mmccrackan commented on src/array_ops.cxx
> +        throw ValueError_exception("Argument 'y' must be a C-contiguous 2d array.");
Sorry for the delay.  I've added the requested changes.  Could you re-approve as my last push undid that.

2024-10-21 14:38 UTC, merged