Adds fitting functionality using Ceres-Solver
simonsobs/so3g pull request #189
Opened 2024-10-29 18:58 UTC by mmccrackan

This branch is an attempt at adding fitting functionality to `so3g` using the `Ceres-Solver` library to support both non-linear least squares and general optimization problems.  It is used to duplicate the existing noise-fitting function in `sotodlib`. The idea of this function is to:

1. Find an initial guess for the white noise by calculating the median of the PSD above an input lower frequency bound.
2. Do a least-squares fit of the 1/f component of the PSD to a power law in logspace to estimate the index and knee frequency. 
3. Run the minimization using a negative log likelihood function as the cost function.

The cost function classes and fitting functions have been written in a model-independent manner, so they should be easy to adapt for other data and model types.   `Ceres` includes options for bounds/constraints and supports auto differentiation so derivatives and gradients don't need be calculated manually.  The general minimization routine for `Ceres` doesn't seem to have uncertainty calculations (its least-squares routines do) so I have manually calculated the inverted Hessian matrix to get the parameter uncertainties.

I put most of the code into new `fitting_ops.cxx` and `fitting_ops.h` files instead of putting it all in `array_ops.cxx`.  I added an `array_ops.h` file to hold shared functions declarations.

I've added a cmake directory with cmake files for `Ceres,` `Eigen`, `Gflag`, and `Glog` with the last 3 being dependencies of `Ceres-Solver`.  We could move these into `spt3g` at some point, but this also seems to work in my tests.  `Eigen` is a nice optimized vector, matrix, and linear algebra library that might be useful on its own, but it is not required to use `Eigen` when working with ceres.

Building the Docker image for tests will take a few minutes longer now as I found that Ceres needed to be built from source as the necessary version doesn't appear to be available through `apt-get libceres-dev`.

2025-01-31 05:37 UTC, mhasself requested changes
Very interesting -- thanks for bringing this in and addressing such an important case.

I can't promise these are all my comments, yet, but it's a start...

2025-01-31 05:37 UTC, mhasself commented on include/array_ops.h
> +T _calculate_median(const T*, const int);
Add newline

2025-01-31 05:37 UTC, mhasself commented on include/fitting_ops.h
> +struct NegLogLikelihood
I think it's important to point out, in the comment and/or name of the class, that this is what you should use for fitting power spectra.  One should use this only on data whose residuals are expected to be Chi2(1)-distributed.  Is it accurate to call it PowerSpectrumCostFunction?

2025-01-31 05:37 UTC, mhasself commented on src/fitting_ops.cxx
> +bool _invert_matrix(const T* matrix, T* inverse, const int n) {
Was this code copyright-free?

2025-01-31 05:37 UTC, mhasself commented on src/fitting_ops.cxx
> +             "  c: uncertaintiy array (float32/64) with dimensions (ndets, nparams). This is modified in place.\n"
For p and c -- do the values going in matter?  Or can it just be zeros/empty?

2025-01-31 05:37 UTC, mhasself commented on src/fitting_ops.cxx
> +             "  f: frequency array (float32/64) with dimensions (nsamps,).\n"
Are there requirements on f?  Must it be positive definite; must it be strictly increasing?

2025-01-31 05:37 UTC, mhasself commented on src/fitting_ops.cxx
> +    int fwhite_size = fwhite_i[1] - fwhite_i[0] + 1;
This looks segfaulty.  Make it robust against fwhite_lower / fwhite_upper pathologically dodging your tests.  A good way is like
```
int fwhite_lo = 0;
while (fwhite_lo < nsamps && f[fwhite_lo] < fwhite_lower)
  fwhite_lo++;

fwhite_hi = fwhite_lo;
whilte (...
```

2025-02-25 20:52 UTC, mmccrackan commented on include/fitting_ops.h
> +struct NegLogLikelihood
Apologies for the late response to this.  Since the cost function classes are model-independent, I wanted to keep the names general instead of tying them to the power spectrum model.  I updated the comment to be more descriptive.

2025-02-25 20:56 UTC, mmccrackan commented on src/fitting_ops.cxx
> +bool _invert_matrix(const T* matrix, T* inverse, const int n) {
I didn't copy this just used basic references, so should be good.  I did cross-check the outputs with a function using LAPACK that we could use instead, though that is much slower for these small matrices.

2025-02-25 20:56 UTC, mmccrackan commented on src/fitting_ops.cxx
> +             "  c: uncertaintiy array (float32/64) with dimensions (ndets, nparams). This is modified in place.\n"
Updated comment to explain that the input values are ignored.

2025-02-25 20:58 UTC, mmccrackan commented on src/fitting_ops.cxx
> +             "  f: frequency array (float32/64) with dimensions (nsamps,).\n"
I think it would have failed previously due to the segfault-prone code you pointed out, but should be fine now.  I added some description to the docstring to be more informative.

2025-02-25 20:59 UTC, mmccrackan commented on src/fitting_ops.cxx
> +    int fwhite_size = fwhite_i[1] - fwhite_i[0] + 1;
Updated.

2025-02-25 20:59 UTC, mmccrackan commented on include/array_ops.h
> +T _calculate_median(const T*, const int);
Done.

2025-03-03 17:22 UTC, mhasself reviewed
Thanks!  Couple minor comments.

Also, can you add a test where the data are noisy, i.e. where the data have Chi2-1 dist from the model?  You can do that by just drawing from normal(model(f)**.5) and then squaring the results.

2025-03-03 17:22 UTC, mhasself commented on src/fitting_ops.cxx
> +    }
I believe this compares an index to a frequency.

When I see a function like this I'm inclined to rewrite it generically -- consider a function that takes double *f and also a vector of f_lims, both assumed increasing, and returns vector of f_lims_idx, with the indices of those f_lims.  There's a lot of specificity here that isn't really needed.  And it would clarify that in all cases you are getting the lowest index `i` s.t. `f[i] >= f_lim`  (not even sure if that's the case here -- because each search loop is written somewhat differently).

2025-03-03 17:22 UTC, mhasself commented on src/fitting_ops.cxx
> +             "  c: output uncertaintiy array (float32/64) with dimensions (ndets, nparams). "
typo

2025-03-03 23:55 UTC, mmccrackan commented on src/fitting_ops.cxx
> +    }
Yeah that was a typo.  I've generalized the function as suggested and do up-front checks on the input frequency values.

2025-03-03 23:58 UTC, mmccrackan commented on src/fitting_ops.cxx
> +             "  c: output uncertaintiy array (float32/64) with dimensions (ndets, nparams). "
Fixed.

2025-03-04 00:03 UTC, mmccrackan commented
> Thanks! Couple minor comments.
> 
> Also, can you add a test where the data are noisy, i.e. where the data have Chi2-1 dist from the model? You can do that by just drawing from normal(model(f)**.5) and then squaring the results.

Added the test with noise. It was a good thing you suggested this as I found that the logger needs to be shut down at the end otherwise it will fail if the fit function is called twice.

2025-05-29 20:06 UTC, mhasself approved these changes

2025-05-29 20:07 UTC, merged