Add c++ jump fixing and finding of slow jumps
simonsobs/so3g pull request #196
Opened 2024-12-26 18:51 UTC by skhrg

Still a draft because my so3g build system is broken rn...

2025-01-13 11:00 UTC, kwolz reviewed
Looks great! Only a single comment.

2025-01-13 11:00 UTC, kwolz commented on src/array_ops.cxx
> +            start = di*nsamp + r.first;
Is it ensured that every r.first (lower end of the jump range) is greater than r.first of the preceding one? I think this is needed for this code to work.

2025-01-13 16:10 UTC, skhrg commented on src/array_ops.cxx
> +            start = di*nsamp + r.first;
Yes, I believe that this is guaranteed by the ranges matrix. Ranges cannot overlap so the `r.first` of a range will always be at least 1 greater than the `r.second` of the preceding one.

2025-01-13 17:05 UTC, mhasself requested changes
Very happy to see this!

Please add smoke tests for these functions.

I would really like you to loosen the requirement on strides[0].  But I suppose it's not urgent for me if it's not urgent for you.

2025-01-13 17:05 UTC, mhasself commented on src/array_ops.cxx
> +            "Subtract fit jump heights from known jump locatations in a float32 array."
Typo "locations".

The description here doesn't really tell someone how to use this function.  Consider expanding this docstring to actually say what is done.  At the very least you should make it more clear that the jumps are treated _cumulatively_, potentially modifying almost every sample.  Something like:

"For each detector, compute the cumulative effect of the jumps identified by the array "heights" and the RangesMatrix "jumps".  For each range in "jumps", the values from "heights" are checked and the size of the jump is either the largest positive or the largest negative number (whichever has the largest absolute value).  The "output" value is the difference of "tod" and the accumulated jump vector."

2025-01-13 18:21 UTC, skhrg commented on src/array_ops.cxx
> +            height = (max(abs(min_h), abs(max_h)) == abs(min_h)) ? min_h : max_h;
Yeah does that test and also sets the value in the same line (also guards against the case where one is an overflow I think)

2025-01-13 18:22 UTC, skhrg commented on src/array_ops.cxx
> +            start = di*nsamp + r.first;
@mhasself can you confirm that what I said above is true?

2025-01-13 19:12 UTC, mhasself commented on src/array_ops.cxx
> +            height = (max(abs(min_h), abs(max_h)) == abs(min_h)) ? min_h : max_h;
Exponential question growth!!  What is "the case where one is an overflow"?  In what sense does this guard against it?  And, are we sure that "guarding against it" is what we want to do, in that case?

2025-01-14 01:55 UTC, skhrg commented on src/array_ops.cxx
> +            height = (max(abs(min_h), abs(max_h)) == abs(min_h)) ? min_h : max_h;
Actually realizing I cut the overflow stuff, that would be:
 `height = (max_h == FLT_MIN ||  min_h == FLT_MIN) ? FLT_MIN : ((max(abs(min_h), abs(max_h)) == abs(min_h)) ? min_h : max_h);`

The reason for including this is because `abs(FLT_MIN)` overflows (I'm pretty sure)  once you flip the sign, I cut it because:

1. If we are in a state to trigger that it means something is going wrong and we probably want to crash anyways
2. I was too lazy to figure out how to generalize since this is a templated function (ie: for doubles you want `DBL_MIN` instead).

2025-01-14 09:56 UTC, mhasself commented on src/array_ops.cxx
> +            height = (max(abs(min_h), abs(max_h)) == abs(min_h)) ? min_h : max_h;
Ok, thanks for making me learn about limits and overflows...

The C++ templated version of FLT_MAX is `std::numeric_limits<T>::max()`, from `#include <limits>`.

Note that FLT_MIN is not negative-almost-infinity.  Rather it's the smallest representable positive number.  So that's not something we'd worry about.

Yes, leaving it simple should just cause things to quietly saturate at +inf / -inf.  That's fine.

Since you have brought me down this rabbit hole, please change the line to:
```
// Decide whether this is a negative or positive jump.
height = (abs(min_h) > abs(max_h)) ? min_h : max_h;
```

That is the payment I demand.

2025-01-15 15:57 UTC, mmccrackan approved these changes
I don't think I have any major comments outside of one quick question.

2025-01-15 15:57 UTC, mmccrackan commented on src/array_ops.cxx
> +            height = (abs(min_h) > abs(max_h)) ? min_h : max_h;
I think the answer is yes, but is this okay if there is a jump at the first or last samples?

2025-01-15 16:24 UTC, skhrg commented on src/array_ops.cxx
> +            height = (abs(min_h) > abs(max_h)) ? min_h : max_h;
Yeah thats fine, the mean level will shift to around the first sample's value in that case, but that should be ok since we will want to mean sub after gapfilling anyways.

2025-01-15 16:32 UTC, mhasself approved these changes
Thanks!

I am only looking the other way on the bulk-reformatting of that test file because it is well-separated from where you made actual changes.

Remember to squash on/before merge.

2025-01-15 16:35 UTC, skhrg commented
> I am only looking the other way on the bulk-reformatting of that test file because it is well-separated from where you made actual changes.

Stupid diffs giving away my love for black...

2025-01-15 16:59 UTC, merged